<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95020a0a617574682e70726f746f12087270632e6175746822120a034b" .
            "6579120b0a036b657918012001280922160a05546f6b656e120d0a05746f" .
            "6b656e18012001280922580a08526573706f6e7365120c0a04636f646518" .
            "0120012805120f0a076d657373616765180220012809120d0a0576616c69" .
            "64180320012808121e0a05746f6b656e18042001280b320f2e7270632e61" .
            "7574682e546f6b656e326f0a0441757468122f0a08476574546f6b656e12" .
            "0d2e7270632e617574682e4b65791a122e7270632e617574682e52657370" .
            "6f6e7365220012360a0d56616c6964617465546f6b656e120f2e7270632e" .
            "617574682e546f6b656e1a122e7270632e617574682e526573706f6e7365" .
            "2200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

