<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Rpc\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpc.message.Common</code>
 */
class Common extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string receive = 1;</code>
     */
    private $receive = '';
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string send = 4;</code>
     */
    private $send = '';
    /**
     * Generated from protobuf field <code>string send_group = 5;</code>
     */
    private $send_group = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $receive
     *     @type string $title
     *     @type string $message
     *     @type string $send
     *     @type string $send_group
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string receive = 1;</code>
     * @return string
     */
    public function getReceive()
    {
        return $this->receive;
    }

    /**
     * Generated from protobuf field <code>string receive = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReceive($var)
    {
        GPBUtil::checkString($var, True);
        $this->receive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string send = 4;</code>
     * @return string
     */
    public function getSend()
    {
        return $this->send;
    }

    /**
     * Generated from protobuf field <code>string send = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSend($var)
    {
        GPBUtil::checkString($var, True);
        $this->send = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string send_group = 5;</code>
     * @return string
     */
    public function getSendGroup()
    {
        return $this->send_group;
    }

    /**
     * Generated from protobuf field <code>string send_group = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSendGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->send_group = $var;

        return $this;
    }

}

