<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Rpc\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rpc.message.Sentry</code>
 */
class Sentry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string projectName = 1;</code>
     */
    private $projectName = '';
    /**
     * Generated from protobuf field <code>string level = 2;</code>
     */
    private $level = '';
    /**
     * Generated from protobuf field <code>string time = 3;</code>
     */
    private $time = '';
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string href = 5;</code>
     */
    private $href = '';
    /**
     * Generated from protobuf field <code>string type = 6;</code>
     */
    private $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $projectName
     *     @type string $level
     *     @type string $time
     *     @type string $message
     *     @type string $href
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string projectName = 1;</code>
     * @return string
     */
    public function getProjectName()
    {
        return $this->projectName;
    }

    /**
     * Generated from protobuf field <code>string projectName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->projectName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string level = 2;</code>
     * @return string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>string level = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time = 3;</code>
     * @return string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>string time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string href = 5;</code>
     * @return string
     */
    public function getHref()
    {
        return $this->href;
    }

    /**
     * Generated from protobuf field <code>string href = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setHref($var)
    {
        GPBUtil::checkString($var, True);
        $this->href = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 6;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

